# Generated by Django 5.0 on 2024-06-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_attendee_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='booking_date',
            field=models.DateField(null=True, blank=True),
        ),
    ]
